---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/logStore/elasticsearch/storage/storageClassName
        value: 'gp3-csi'
    target:
      kind: ClusterLogging
      name: instance
