---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: loki-storage-bucket
  namespace: netobserv
  labels:
    app: noobaa
    bucket-provisioner: openshift-storage.noobaa.io-obc
    noobaa-domain: openshift-storage.noobaa.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  objectBucketName: loki-storage-bucket
  bucketName: obc-netobserv-loki-storage-bucket
  storageClassName: openshift-storage.noobaa.io
