---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-secret-sync
  namespace: netobserv
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: loki-secret-sync
  namespace: netobserv
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - exec
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loki-secret-sync
  namespace: netobserv
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: loki-secret-sync
subjects:
  - kind: ServiceAccount
    name: loki-secret-sync
    namespace: netobserv
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: loki-secret-sync
  namespace: netobserv
spec:
  schedule: "0/10 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: loki-secret-sync
            image: registry.redhat.io/openshift4/ose-cli:latest
            imagePullPolicy: IfNotPresent
            command:
              - /bin/bash
              - -c
              - |
                #!/usr/bin/env bash

                until oc get secret -n netobserv loki-storage-bucket; do
                    echo "Waiting for loki-storage-bucket secret to be created"
                    sleep 5
                done

                cat <<EOF | oc apply -f -
                apiVersion: v1
                kind: Secret
                metadata:
                  name: loki-s3
                  namespace: netobserv
                type: Opaque
                stringData:
                  access_key_id: $(oc get secret -n netobserv loki-storage-bucket -o json | jq -rMc '.data.AWS_ACCESS_KEY_ID' | base64 -d)
                  access_key_secret: $(oc get secret -n netobserv loki-storage-bucket -o json | jq -rMc '.data.AWS_SECRET_ACCESS_KEY' | base64 -d)
                  bucket_name: loki-storage-bucket
                  endpoint: s3.openshift-storage.svc:443
                  region: the-moon
                EOF
          serviceAccountName: loki-secret-sync
          restartPolicy: OnFailure