---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-secret-sync
  namespace: netobserv
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: loki-secret-sync
  namespace: netobserv
  annotations:
    argocd.argoproj.io/sync-wave: "2"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - exec
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loki-secret-sync
  namespace: netobserv
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: loki-secret-sync
subjects:
  - kind: ServiceAccount
    name: loki-secret-sync
    namespace: netobserv
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: loki-secret-sync
  namespace: netobserv
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: loki-secret-sync
            image: registry.redhat.io/openshift4/ose-cli:latest
            imagePullPolicy: IfNotPresent
            command:
              - /bin/bash
              - -c
              - |
                #!/usr/bin/env bash

                until oc get secret -n netobserv loki-storage-bucket; do
                    echo "Waiting for loki-storage-bucket secret to be created"
                    sleep 5
                done

                KEY_ID=$(oc get secret -n netobserv loki-storage-bucket --template={{.data.AWS_ACCESS_KEY_ID}} | base64 -d)
                KEY_SECRET=$(oc get secret -n netobserv loki-storage-bucket --template={{.data.AWS_SECRET_ACCESS_KEY}} | base64 -d)

                cat <<EOF | oc apply -f -
                apiVersion: v1
                kind: Secret
                metadata:
                  name: loki-s3
                  namespace: netobserv
                type: Opaque
                stringData:
                  access_key_id: ${KEY_ID}
                  access_key_secret: ${KEY_SECRET}
                  bucketnames: loki-storage-bucket
                  endpoint: s3.openshift-storage.svc:443
                  region: the-moon
                EOF
          serviceAccountName: loki-secret-sync
          restartPolicy: OnFailure