---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - debug-receiver.yml
  - secret-alertmanager-main.yml
  - pod-issues-PrometheusRule.yml
  - quota-high-usage-PrometheusRule.yml
  - bad-workloads.yml