# oc patch console.operator cluster --type json -p '[{"op": "add", "path": "/spec/plugins", "value": ["gitops-plugin"]}]'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: patch-console
  namespace: openshift-netobserv-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patch-console
rules:
  - apiGroups:
      - operator.openshift.io
    resources:
      - consoles
    verbs:
      - get
      - list
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: patch-console
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: patch-console
subjects:
  - kind: ServiceAccount
    name: patch-console
    namespace: openshift-netobserv-operator
---
apiVersion: batch/v1
kind: Job
metadata:
  name: enable-netobserv-plugin
  namespace: openshift-netobserv-operator
spec:
  selector: {}
  template:
    metadata:
      name: enable-netobserv-plugin
    spec:
      containers:
        - name: enable-netobserv-plugin
          image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/bash
            - -c
            - |
              #!/usr/bin/env bash

              oc patch console.operator cluster --type json -p '[{"op": "add", "path": "/spec/plugins", "value": ["netobserv-plugin"]}]'
      restartPolicy: Never
      serviceAccountName: patch-console
