---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: splunk-hec-route-job
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: splunk-hec-route-job
  annotations:
    argocd.argoproj.io/sync-wave: "2"
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - exec
  - apiGroups:
      - "operator.openshift.io"
    resources:
      - ingresscontrollers
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
      - delete
  - apiGroups:
      - "route.openshift.io"
    resources:
      - routes
      - routes/custom-host
    verbs:
      - get
      - list
      - create
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: splunk-hec-route-job
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: splunk-hec-route-job
subjects:
  - kind: ServiceAccount
    name: splunk-hec-route-job
    namespace: openshift-splunk
