---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-splunk

resources:
  - namespace.yml
  - rbac.yml
  - instance.yml
  - route.yml
  - consolelink-job.yml
  - consolelink-rbac.yml
