---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Override the namespace of all of the resources we manage.
namespace: openshift-vector-aggregator

#images:
#  # Override the Vector image to pin the version used.
#  - name: timberio/vector
#    newName: timberio/vector
#    newTag: 0.34.0-distroless-libc

resources:
  # The namespace previously created to keep the resources in.
  - namespace.yml
  - https://raw.githubusercontent.com/vectordotdev/vector/master/distribution/kubernetes/vector-aggregator/configmap.yaml
  - https://raw.githubusercontent.com/vectordotdev/vector/master/distribution/kubernetes/vector-aggregator/service-headless.yaml
  - https://raw.githubusercontent.com/vectordotdev/vector/master/distribution/kubernetes/vector-aggregator/service.yaml
  - https://raw.githubusercontent.com/vectordotdev/vector/master/distribution/kubernetes/vector-aggregator/serviceaccount.yaml
  - https://raw.githubusercontent.com/vectordotdev/vector/master/distribution/kubernetes/vector-aggregator/statefulset.yaml
