---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/redhat-cop/gitops-catalog/openshift-logging/instance/base


patches:
  - patch: |-
      - op: replace
        path: /spec/logStore/elasticsearch/storage/storageClassName
        value: 'lvms-vg1'
    target:
      kind: ClusterLogging
      name: instance

  - patch: |-
      - op: replace
        path: /spec/collection/type
        value: 'vector'
    target:
      kind: ClusterLogging
      name: instance

  - patch: |-
      - op: replace
        path: /spec/logStore/elasticsearch/storage/size
        value: '50G'
    target:
      kind: ClusterLogging
      name: instance

  - patch: |-
      - op: remove
        path: /spec/collection/logs
    target:
      kind: ClusterLogging
      name: instance

  - patch: |-
      - op: remove
        path: /spec/curation
    target:
      kind: ClusterLogging
      name: instance

  - patch: |-
      - op: replace
        path: /spec/href
        value: 'https://kibana-openshift-logging.apps.mega-sno.d70.lab.kemo.network'
    target:
      kind: ConsoleLink
      name: kibana-public-url